server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/juanecox/MicreserviciosV2
          search-paths: config-data
  application:
    name: config-service
    
#notas
#default-label es la rama
#application name es el nomre de este proyecto de configuracion
#serach-path ahi se encuentran los archivos de configuracion de cada microservicio