server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: rentas
          uri: https://github.com/juanecox/MicreserviciosV2
          search-paths: config-data
  application:
    name: config-service