server:
  port: 8003  
spring:
  application:
    name: bike-service
  datasource: 
    url: jdbc:mysql://localhost:3306/microservicio-examen
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate.ddl-auto: update
    show-sql: true
